### ISSUE TITLE
Main.gmk is not cross-build-friendly

### ISSUE THREAD

**Issue by knn-k** [ibmruntimes/openj9-openjdk-jdk11#133]
Running `make all` in a cross-building environment fails with the target `test-image-openj9`, because it runs `$(JDK_OUTPUTDIR)/bin/java -version` on an incompatible platform.

**Comment by knn-k** [comment]
I found this problem from building the aarch64 runtime in an x86-64 Linux environment.
`make all` for aarch64 successfully finishes when I comment out the line for `java-version.txt` in `closed/make/Main.gmk`.

How can I make `Main.gmk` cross-build-friendly?

**Comment by pshipton** [comment]
@andrew-m-leonard @keithc-ca

**Comment by keithc-ca** [comment]
That shouldn't be hard to address; give me a few minutes.

**Comment by keithc-ca** [comment]
See:
* jdk8 - https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/269
* jdk11 - https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/134
* jdk12 - https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/14
* jdk13 - https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/76

**Comment by pshipton** [comment]
The changes are merged. I'll close this assuming it is now resolved.

**Comment by knn-k** [comment]
Thank you.  It works.
