### ISSUE TITLE
Questions for jdk version infos

### ISSUE THREAD

**Issue by gaolibj** [ibmruntimes/openj9-openjdk-jdk11#142]
We build a Java11 on IBM i platform.  Without adding any specify options related to jdk versions in configuration phase.   Following is the output of "java -version".

bash-4.4$ bin/java -version
openjdk version **"11.0.1-internal" 2018-10-16**
OpenJDK Runtime Environment (build **11.0.1**-internal+0-adhoc.gaolibj.openj9-openjdk-jdk11)
Eclipse OpenJ9 VM (build openj9-0.11.0, JRE 11 OS/400 ppc64-64-Bit Compressed References 20190311_000000 (JIT enabled, AOT enabled)
OpenJ9   - 090ff9d
OMR      - ea548a6
JCL      - d445507 based on **jdk-11.0.3+2**)

Get source codes with following steps.
-   git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
-   cd openj9-openjdk-jdk11
-   git checkout openj9-0.11
-   get_source.sh

The string **"11.0.1" 2018-10-16** is hardcoded in file openj9-openjdk-jdk11/make/autoconf/version-numbers as below.
```
DEFAULT_VERSION_FEATURE=11
DEFAULT_VERSION_INTERIM=0
DEFAULT_VERSION_UPDATE=1
DEFAULT_VERSION_PATCH=0
DEFAULT_VERSION_DATE=2018-10-16
```

The string **jdk-11.0.3+2** is set with OPENJDK_TAG in file
 openj9-openjdk-jdk11/closed/autoconf/custom-hook.m4.

```
AC_DEFUN_ONCE([OPENJDK_VERSION_DETAILS],
[
  OPENJDK_SHA=`git -C $TOPDIR rev-parse --short HEAD`
  LAST_TAGGED_SHA=`git -C $TOPDIR rev-list --tags="jdk-11*" --topo-order --max-count=1 2>/dev/null`
  if test "x$LAST_TAGGED_SHA" != x; then
    OPENJDK_TAG=`git -C $TOPDIR describe --tags "$LAST_TAGGED_SHA"`
  else
    OPENJDK_TAG=
  fi
  AC_SUBST(OPENJDK_SHA)
  AC_SUBST(OPENJDK_TAG)

  # Outer [ ] to quote m4.
  [ USERNAME=`$ECHO "$USER" | $TR -d -c '[a-z][A-Z][0-9]'` ]
  AC_SUBST(USERNAME)
])
```

I want to know why it's different.  We only work on branch openj9-0.11. 
If change the command as below,  it  can get string ”jdk-11.0.1+13" instead of ”jdk-11.0.3+2".  

bash-4.4$ git describe --tags `git rev-list -1 openj9-0.11`
jdk-11.0.1+13-654-gd445507     

We want  these two versions to be consistent like it on AIX.

bash-4.4$ bin/java -version
openjdk version **"11.0.2"** 2019-01-15
OpenJDK Runtime Environment AdoptOpenJDK (build **11.0.2+9**)
Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.12.1, JRE 11 AIX ppc64-64-Bit Compressed References 20190204_121 (JIT enabled, AOT enabled)
OpenJ9   - 90dd8cb
OMR      - d2f4534
JCL      - 289c70b based on **jdk-11.0.2+9**)

I know there are some options can be used to effect version string,  like --with-version-date,--with-version-string and --with-version-<part>.  But  seems it will not effect OPENJDK_TAG.

How can I make the version numbers be consistent? Thanks.

**Comment by gaolibj** [comment]
Besides, I noticed that all jdks download from [](https://adoptopenjdk.net/) has the string “AdoptOpenJDK”.  Is it a MUST string or only for the jdks distributed at [](https://adoptopenjdk.net/) .  Thanks.

**Comment by gaolibj** [comment]
BTW, the source code related to version string is same as AIX.

**Comment by pshipton** [comment]
@gaolibj The openj9-0.11 branch corresponds to the OpenJ9 0.11.0 release from Oct 2018, which is built with OpenJDK 11.0.1 so the hard coded 11.0.1 and `2018-10-16` date are correct. The `based on jdk-11.0.3+2` is not correct, and should be getting the latest tag on the branch being built. @keithc-ca 

The "AdoptOpenJDK" string is only for builds created and distributed from AdoptOpenJDK.

FYI
The OpenJ9 0.12.0 and 0.12.1 releases correspond to OpenJDK 11.0.2 from Jan 2019, for which the extensions openj9-0.12 or openj9-0.12.1 branches should be used.

The upcoming OpenJ9 0.14.0 release in April will correspond to OpenJDK 11.0.3 release in April. There is no branch for this yet, it will be created closer to the release date.

Note the Eclipse OpenJ9 releases are documented here https://projects.eclipse.org/projects/technology.openj9

**Comment by keithc-ca** [comment]
The code in `custom-hook.m4` that tries to find the most recent tag is broken: instead it considers ***all*** tags matching the name pattern. I'll see if that can be fixed.

**Comment by gaolibj** [comment]
Thanks for the explanation.   fyi.   We used following command to get the latest tag name in current branch in Git.  It works for me :-)
bash-4.4$ git describe --abbrev=0 --tags
   jdk-11.0.1+13

**Comment by keithc-ca** [comment]
I think we used that command in the past, but it yielded bad answers in some cases.

**Comment by keithc-ca** [comment]
> I think we used that command in the past, but it yielded bad answers in some cases.

For example, with the head of the openj9 branch (`3cd1a589af`) checked out, `git describe --abbrev=0 --tags` answers `jdk-11.0.2+2` instead of `jdk-11.0.3+2` as we would like.

**Comment by keithc-ca** [comment]
I think this has been thoroughly addressed in all current branches.

**Comment by gaolibj** [comment]
Thanks.  Will verify it when we build with new branches.
