### ISSUE TITLE
java.lang.InternalError: Failed to load default.policy with AdoptOpenJDK 11.0.2 with OpenJ9 used through Windows UNC 

### ISSUE THREAD

**Issue by lumpfish** [ibmruntimes/openj9-openjdk-jdk11#148]
Issue reported at eclipse/openj9:
https://github.com/eclipse/openj9/issues/4927

openjdk fix was created for jdk13, backported to jdk12, but not jdk11.

Short term resolution is to backport the fix to openj9-openjdk-jdk11: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8218618

Longer term solution is to backport the fix to openjdk jdk11u.

**Comment by groeges** [comment]
@lumpfish This was back-ported to jdk11u in this issue: https://bugs.openjdk.java.net/browse/JDK-8221990 and the original openj9 issue https://github.com/eclipse/openj9/issues/4927 is now closed, so I will close this issue.
