### ISSUE TITLE
openj9-0.11 released zip doesn't include .git directory

### ISSUE THREAD

**Issue by gaolibj** [ibmruntimes/openj9-openjdk-jdk11#150]
I'm trying to build Java 11 with downloading sources from 
https://github.com/ibmruntimes/openj9-openjdk-jdk11/archive/openj9-0.11.zip
https://github.com/eclipse/openj9-omr/archive/openj9-0.11.0.tar.gz
https://github.com/eclipse/openj9/archive/openj9-0.11.0.zip

There is no .git directory  in zip file.   BUT seems java 11 build depends on information under .git dir, like getting component(OMR/OpenJ9/JCL) version from the last commit id or tag. 

Can you create releases for the OpenJ9 release branch, like openj9-0.11?  Then we can use zip/tar files directly for build.

**Comment by gaolibj** [comment]
Actually, we are trying to build it into RPM format.   Seems "git clone" and "git checkout" is not a formal way to get sources.  The source codes will be changed if there is any commit to the branch.
So, we are querying if  there are release zip/tar files.  Thanks.

**Comment by pshipton** [comment]
@andrew-m-leonard @lumpfish 
I believe @gaolibj is requesting a tag to be created on the shas which are used for the openj9 releases.

At one time this wasn't possible because creation of the tag would cause AdoptOpenJDK builds to fail. Not sure if this has been resolved.

**Comment by keithc-ca** [comment]
I believe that's the design intent of downloading snapshots from github: just the source with no `.git` directory. Given that, a tag wouldn't help because it resides in that `.git` folder.

**Comment by keithc-ca** [comment]
Now that #168 is merged, this should no longer be an issue.
