### ISSUE TITLE
Support for openssl 1.0.1

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk11#159]
Support was added for openssl 1.0.2, however some older OSes like RHEL 6 and Debian 8 are still using the 1.0.1 version. When OpenJDK + OpenJ9 runs on these older OSes, a supported version of openssl is unlikely to be found. The crypto will revert to the java implementation which doesn't perform well with OpenJ9.

There is a version check in the openssl support code. This can be modified to accept the 1.0.1 version as well, and then run testing to confirm if it is working.
https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/5c13382d6b3c1a1e2ef5dd48128957adef7a60bc/closed/src/java.base/share/native/libjncrypto/NativeCrypto.c#L196

See also https://github.com/AdoptOpenJDK/openjdk-build/issues/1039

**Comment by pshipton** [comment]
@groeges @andrew-m-leonard @sxa555 @ashbm5 @jerrylui803 @vij.singh

**Comment by pshipton** [comment]
@vij-singh

**Comment by groeges** [comment]
@pshipton How urgent is it to get the support for OpenSSL 1.1 added? 
Does it need to be resolved before we do the quarterly release? 
Do we just want to support OpenSSl 1.0.1 at runtime, or also at build time?

**Comment by sxa555** [comment]
1.0.1 appears to work ok if I disable the version checks in `NativeCrypto.cpp`:

```
[jenkins@build-joyent-centos69-x64-1 sxa]$ openj9-openjdk-jdk11/build/linux-x86_64-normal-server-release/jdk/bin/java -Djdk.nativeCryptoTrace=true CryptoTest
MessageDigest load - using Native crypto library.
CipherCore Load - using native crypto library.
Crypto test COMPLETED
```

**Comment by pshipton** [comment]
@groeges It's too late to be adding features to the quarterly release, it should go into the next release. However the change seems simple, we should try it asap to determine the effort involved.

Supporting 1.0.1 only at runtime is fine with me.

@sxa555 note the CryptoTest just ensures the library can load, it doesn't actually do any crypto operations.

**Comment by groeges** [comment]
The fact that the library was loaded does indicate that all the symbols have been found and the crypto operations should be OK. Will await any testing from Shelley to determine if this is working as expected.

**Comment by groeges** [comment]
This is also needed for JDK8, 12 and next (13).

PR's for each of these releases are:
JDK8:  https://github.com/ibmruntimes/openj9-openjdk-jdk8/pull/289
JDK11: https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/162
JDK12: https://github.com/ibmruntimes/openj9-openjdk-jdk12/pull/43
JDK13: https://github.com/ibmruntimes/openj9-openjdk-jdk/pull/96

**Comment by groeges** [comment]
These PRs have all been merged now, so closing the issue. 
Any problems that arise from this will need to be raised in separate issues.
