### ISSUE TITLE
Number of cpus on AIX isn't determined correctly

### ISSUE THREAD

**Issue by AdamBrousseau** [ibmruntimes/openj9-openjdk-jdk11#17]
Copied from ibmruntimes/openj9-openjdk-jdk8#57

If smt is enabled the correct number of processors is not correct on configure.

There are a number of ways that can be used to determine actual number of processors, I found this works for me on the systems I have access to, smt enabled or not at time of configure

`--with-jobs='pmcycles -m | wc -l | awk '{print $1}''`

**Comment by groeges** [comment]
@andrew-m-leonard Didn't you submit an OpenJDK contribution for this? 
If so, is this resolved and should the issue now be closed?

**Comment by AdamBrousseau** [comment]
I thought so as well but I tested it last week and it didn't seem to work.
https://github.com/eclipse/openj9/pull/5920

**Comment by andrew-m-leonard** [comment]
this has been contributed to openjdk, but not backported.
We could try and request a backport, but I suspect they may not consider it a significant issue to backport

**Comment by andrew-m-leonard** [comment]
This has now been backported to jdk11u https://hg.openjdk.java.net/jdk-updates/jdk11u/rev/9df633d78584

**Comment by pshipton** [comment]
@andrew-m-leonard please see the previous comment.

**Comment by AdamBrousseau** [comment]
From an internal issue (Aug 27)
>This is in jdk8u-dev and will get promoted to jdk8u this week, and assuming RedHat/Oracle tag the jdk8u232-b05 build this week we will pick that up... so my guess would be end of this week.

Related https://github.com/eclipse/openj9/pull/5920
