### ISSUE TITLE
Define openj9-0.14.2 branch content

### ISSUE THREAD

**Issue by lumpfish** [ibmruntimes/openj9-openjdk-jdk11#174]
The openj9-0.14.2 branch has been created for the creation of the jdk-11.0.3+7_openj9-0.14.2 adoptopenjdk.

It was created from the openj9-0-14.0 branch with just the changes to check out the openj9-0-14-2 tags from the eclipse/openj9 and eclipse/omr repositories and to update the extensions version.

This issue is to define which additional commits need to be included in this release.

(Note that the commit which created the openj9-0.14.2 branch has the commit message "Create openj9-0.14.0 branch" in error.

**Comment by pshipton** [comment]
#162 Add support to use OpenSSL 1.0.1 at runtime
#168 Set OPENJDK_TAG from merged openjdk level

**Comment by pshipton** [comment]
I've also already merged #171 and will merge #173 later today.

**Comment by lumpfish** [comment]
Created https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/175 for OPENJDK_TAG and openssl 1.0.1

**Comment by pshipton** [comment]
Reviewed and merged #175
