### ISSUE TITLE
libj9zlib29.so build failed on aix 7.1

### ISSUE THREAD

**Issue by bjxiangy** [ibmruntimes/openj9-openjdk-jdk11#18]
xlc_r -q64 -qmkshrobj -Wl,-brtl -Wl,-G -Wl,-bernotok -Wl,-bnoentry -Wl,-bmap:j9zlib.map -Wl,-bE:j9zlib.exp -L/usr/lib/threads \
         -L. -L../ -L../lib/ -o ../libj9zlib29.so \
        zlib_copyright.o adler32.o compress.o crc32.o deflate.o infback.o inffast.o inflate.o inftrees.o trees.o uncompr.o zutil.o \
            -lc_r -lm -lpthreads
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_adler32
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_compress
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_compress2
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_crc32
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflate
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateCopy
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateEnd
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateInit_
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateInit2_
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateParams
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateReset
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_deflateSetDictionary
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_get_crc_table
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflate
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateCopy
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateEnd
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateInit_
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateInit2_
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateReset
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateSetDictionary
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateSync
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_inflateSyncPoint
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_uncompress
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_zError
ld: 0711-319 WARNING: Exported symbol not defined: j9zlib_zlibVersion
ld: 0711-244 ERROR: No csects or exported symbols have been saved.
../makelib/targets.mk:359: recipe for target '../libj9zlib29.so' failed
gmake[5]: *** [../libj9zlib29.so] Error 8
gmake[5]: Leaving directory '/home/builder/openj9-openjdk-jdk11/build/aix-ppc64-normal-server-release/vm/zlib'
makefile:101: recipe for target 'j9zlib' failed
gmake[4]: Leaving directory '/home/builder/openj9-openjdk-jdk11/build/aix-ppc64-normal-server-release/vm'
gmake[4]: *** [j9zlib] Error 2
/home/builder/openj9-openjdk-jdk11/closed/OpenJ9.gmk:422: recipe for target 'build-j9' failed
gmake[3]: *** [build-j9] Error 2
/home/builder/openj9-openjdk-jdk11/closed/make/Main.gmk:39: recipe for target 'j9vm-build' failed
gmake[2]: *** [j9vm-build] Error 2

ERROR: Build failed for target 'all' in configuration 'aix-ppc64-normal-server-release' (exit code 2) 

=== Make failed targets repeated here ===
../makelib/targets.mk:359: recipe for target '../libj9zlib29.so' failed
makefile:101: recipe for target 'j9zlib' failed
/home/builder/openj9-openjdk-jdk11/closed/OpenJ9.gmk:422: recipe for target 'build-j9' failed
/home/builder/openj9-openjdk-jdk11/closed/make/Main.gmk:39: recipe for target 'j9vm-build' failed
=== End of repeated output ===

Hint: Try searching the build log for the name of the first failed target.
Hint: See doc/building.html#troubleshooting for assistance.

/home/builder/openj9-openjdk-jdk11/make/Init.gmk:300: recipe for target 'main' failed
make[1]: *** [main] Error 2
/home/builder/openj9-openjdk-jdk11/make/Init.gmk:186: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by andrew-m-leonard** [comment]
AIX 7.1 builds fine now
