### ISSUE TITLE
loadquery failed (12 Not enough space) error reported

### ISSUE THREAD

**Issue by groeges** [ibmruntimes/openj9-openjdk-jdk11#192]
Following an issue: https://github.com/eclipse/openj9/issues/5530 which was resolved a strange error is now reported 'loadquery failed (12 Not enough space)`. A fix needs to be identified and contributed to the upstream projects in order to not display this error message.

**Comment by groeges** [comment]
Issue is related to a buffer not being large enough and therefore causing the error to be dispayed. 
This has been discussed on the openjdk mailing lists and deemed that the size of the buffer should be increased. 

Will create a build that the reporter can use in order to determine whether the new size of the buffer is suitable for him and stops the error from being displayed.

**Comment by pshipton** [comment]
@mvdobrinin

**Comment by groeges** [comment]
@mvdobrinin I have created a new jdk11 for AIX containing the fix. Would you be able to test it for me to ensure the increase in the dladdr buffer is suitable for the library you are loading. If so I can send it to the email address for your id, unless you have another method you prefer?

**Comment by mvdobrinin** [comment]
@groeges Sorry for late reply. I would be happy to test it. I'll keep an eye on my inbox. 😀

**Comment by groeges** [comment]
An issue has been raised in the jbs system: https://bugs.openjdk.java.net/browse/JDK-8226468 and a fix has been implemented in jdk/jdk (which was jdk14): http://hg.openjdk.java.net/jdk/jdk/rev/c749ecf599c0 which has increased the size of the buffer used. 

With the increased size of the buffer the error should no longer be reported. I am working on getting this back-ported to jdk11 (and possible jdk12 & jdk13).

**Comment by groeges** [comment]
Code has ben back-ported to jdk11. Issue should now be resolved.
