### ISSUE TITLE
MethodTypeForm differs between JDK11 and JDK14

### ISSUE THREAD

**Issue by babsingh** [ibmruntimes/openj9-openjdk-jdk11#301]
[MethodTypeForm JDK11](https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/src/java.base/share/classes/java/lang/invoke/MethodTypeForm.java)

[MethodTypeForm JDK14](https://github.com/ibmruntimes/openj9-openjdk-jdk14/blob/openj9/src/java.base/share/classes/java/lang/invoke/MethodTypeForm.java)

@andrew-m-leonard In `MethodTypeForm`, field names have changed between JDK11 and JDK14. Do we plan to backport the JDK14 `MethodTypeForm` changes to JDK11 and JDK8?

fyi - @fengxue-IS

**Comment by andrew-m-leonard** [comment]
This is probably a question for RedHat who maintain jdk8 & 11. Do you know what openjdk bug (bugs.openjdk.java.net) did the change in jdk14? we can then request a backport..

**Comment by DanHeidinga** [comment]
We should also have a reason to provides benefit to the whole OpenJDK community before we request a backport.

@babsingh what issue are you running into that you want this backported?

**Comment by babsingh** [comment]
There is no bug to be reported. The initial `MethodType and MemberName` changes for `adopting OpenJDK MethodHandles` didn't work with JDK14. This was due to the change in `MethodTypeForm` field names between JDK8/11 and JDK14. If the changes won't be backported, then we will need to support two variants of the field in OpenJ9 (vmconstantpool ... VM and JIT methods).

I just wanted to know if it's possible to backport such changes since it will make OpenJ9 development consistent and cleaner across JDKs 8/11/14. But, backporting these changes won't be possible since we don't have a strong justification which benefits the whole OpenJDK community. Thus, I am closing this issue.

**Comment by DanHeidinga** [comment]
> If the changes won't be backported, then we will need to support two variants of the fields in OpenJ9 (vmconstantpool ... VM and JIT methods).

If these are only the vmconstantpool fields, then we should be OK as the vm constantpool tool supports aliases for fields.

**Comment by babsingh** [comment]
fyi @fengxue-IS Example of field alias ... https://github.com/eclipse/openj9/blob/master/runtime/oti/vmconstantpool.xml#L152-L154
```
<fieldref class="java/lang/String" name="value" signature="[B" versions="9-">
	<fieldalias name="value" signature="[C" versions="8"/>
</fieldref>
```

**Comment by fengxue-IS** [comment]
We would still need to versioning of the usage since the data stored in the field changed between versions. (14+ no longer requires unpacking operation)
