### ISSUE TITLE
different behavior of Charset.defaultCharset() between Java 8 and Java 11 when file.encoding is set

### ISSUE THREAD

**Issue by bjxiangy** [ibmruntimes/openj9-openjdk-jdk11#367]
On AIX, use following code to get the default charset.  On AIX, by default, it is IS8859-1.  If I specify -Dfile.encoding=Cp037,  it returned UTF-8 as default charset.  But with Java 8, it could return IBM037 as default.  

public class CheckVM {
        public static void main(String[] args) {
                System.out.println("Default Charset: " + Charset.defaultCharset());
        }
 
}

**Comment by pshipton** [comment]
IBM037 is an extended encoding in Java11+. It seems this is a known problem that won't be fixed https://bugs.openjdk.java.net/browse/JDK-8081440

**Comment by bjxiangy** [comment]
Thanks for the information!  The issue mentioned that file.encoding is not recommended.  Do you know some formal documentation about this?  In Java 8, it is not disabled and it works as user "expected".  This may block migration to Java 11 if customer rely on it heavily.

**Comment by pshipton** [comment]
The point is that "file.encoding" isn't formally supported. While it works for some cases, it isn't part of the java spec. It works in Java 11 as well for charsets that are in the basic encoding set, see https://docs.oracle.com/en/java/javase/11/intl/supported-encodings.html
For encodings in the extended set, they are detected from the OS so if the OS is configured to use IBM037 then the Charset.defaultCharset() should reflect this.

**Comment by pshipton** [comment]
Also came across this one https://bugs.openjdk.java.net/browse/JDK-4163515

**Comment by bjxiangy** [comment]
Thank you for the information.  It is clear to me.

**Comment by pshipton** [comment]
Perhaps not helpful for your purposes, but FYI the following upcoming change https://github.com/eclipse/openj9/pull/11387 which uses sun.stdout.encoding and sun.sterr.encoding to set the Charset for System.out and System.err.
