### ISSUE TITLE
jps and jstat support in jdk11

### ISSUE THREAD

**Issue by gaolibj** [ibmruntimes/openj9-openjdk-jdk11#375]
From issue [https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/1](url), seems following are unsupported executable.   But they are still in jdk11 builds.  Have a quick try and found the function is limited compared with the tools in Hotspot jvm.  Just want to confirm if they are work as design.     Thanks.

jinfo
jps
jmap
jstack
jstat 

e.g  
**jstat in hotspot JVM on AIX.**

bash-4.2$ jstat -options
-class
-compiler
-gc
-gccapacity
-gccause
-gcmetacapacity
-gcnew
-gcnewcapacity
-gcold
-gcoldcapacity
-gcutil
-printcompilation

**jstat in J9 JVM on AIX**
bash-4.2$ jstat -options
-class

**Comment by pshipton** [comment]
The tools are working as designed for OpenJ9. Given the resource available, some popular features were implemented.

See the following documentation.

https://eclipse.github.io/openj9-docs/tool_migration
https://www.eclipse.org/openj9/docs/tool_jcmd/
https://www.eclipse.org/openj9/docs/tool_jmap/
https://www.eclipse.org/openj9/docs/tool_jps/
https://www.eclipse.org/openj9/docs/tool_jstack/
https://www.eclipse.org/openj9/docs/tool_jstat/
https://eclipse.github.io/openj9-docs/tool_migration/#java-statistics-monitoring-jstat-tool

**Comment by gaolibj** [comment]
Got it.  Thanks.
