### ISSUE TITLE
test/jdk/TEST.ROOT udpate to provide openj9's configuration 

### ISSUE THREAD

**Issue by sophia-guo** [ibmruntimes/openj9-openjdk-jdk11#5]
Running regression tests and got:

04:55:29 Exception in thread "main" java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
04:55:29     at sun.hotspot.WhiteBox.<clinit>(WhiteBox.java:66)
04:55:29     at requires.VMProps.<clinit>(VMProps.java:57)
04:55:29     at java.lang.Class.forNameImpl(java.base@11/Native Method)
04:55:29     at java.lang.Class.forName(java.base@11/Class.java:335)
04:55:29     at com.sun.javatest.regtest.agent.GetJDKProperties.run(GetJDKProperties.java:63)
04:55:29     at com.sun.javatest.regtest.agent.GetJDKProperties.main(GetJDKProperties.java:46)
04:55:29 Error: failed to get JDK properties for /home/jenkins/workspace/openjdk11_j9_openjdktest_x86-64_linux/openjdkbinary/j2sdk-image/bin/../bin/java -ea -esa -Xmx512m -Xcompressedrefs; exit code 1

https://ci.adoptopenjdk.net/view/all/job/openjdk11_j9_openjdktest_x86-64_linux/3/console

**Comment by andrew-m-leonard** [comment]
This should no longer be seen now
