### ISSUE TITLE
Release 11.0.15 breaks JDBC connection to DB2 on Cloud

### ISSUE THREAD

**Issue by lenzch** [ibmruntimes/openj9-openjdk-jdk11#546]
Hi,

This may not be the right place to put this issue, but I'm not 100% sure, what the root cause is.
I have a Java EE application, that access a DB2 on IBM cloud and the application used to work w/o issues.
The application uses the Liberty for Java [Buildpack](https://cloud.ibm.com/docs/cloud-foundry-public?topic=cloud-foundry-public-cloud-foundry-public-release-notes).

With the recent update of the Buildpack the application fails to connect to the database.

I was able to track the issue down to the change in the used Java JRE. With ibm-semeru-open-jre_x64_linux_11.0.14.1_1_openj9-0.30.1 all is fine. And with the current ibm-semeru-open-jre_x64_linux_11.0.15_10_openj9-0.32.0 I see messages like this:

```
[INFO] Caused by: com.ibm.db2.jcc.am.SqlException: [jcc][t4][20133][12451][4.29.24] Caught NoSuchAlgorithmException while doing SSL Connection.  See attached Throwable for details. ERRORCODE=-4499, SQLSTATE=null
[INFO] 	at com.ibm.db2.jcc.am.b7.a(b7.java:794)
[INFO] 	at com.ibm.db2.jcc.am.b7.a(b7.java:66)
[INFO] 	at com.ibm.db2.jcc.am.b7.a(b7.java:98)
[INFO] 	at com.ibm.db2.jcc.t4.w.run(w.java:287)
[INFO] 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:747)
[INFO] 	at com.ibm.db2.jcc.t4.a0.a(a0.java:435)
[INFO] 	... 28 more
[INFO] Caused by: java.security.NoSuchAlgorithmException: SSL_TLSv2 SSLContext not available
[INFO] 	at java.base/sun.security.jca.GetInstance.getInstance(GetInstance.java:159)
[INFO] 	at java.base/javax.net.ssl.SSLContext.getInstance(SSLContext.java:168)
[INFO] 	at com.ibm.db2.jcc.t4.w.run(w.java:141)
[INFO] 	... 30 more
```

Here is some sample code that reflects the issue:

```java
     public static Connection getConnectionToDatabase() throws SQLException {
        final var jdbcString = "jdbc:db2://HOSTNAME.databases.appdomain.cloud:31322/bludb:"
                + "user=USERNAME;" + "password=PASSWORD;" + 
                 "sslConnection=true;" +
                 "traceLevel=TRACE_ALL;" +
                "traceFile=jcctrace;";
        var conn = DriverManager.getConnection(jdbcString);
        System.out.println("Connected to database");
        return conn;
    }
```

The trace file shows the same message regarding the `NoSuchAlgorithmException`.

Any help or hint is appreciated.

**Comment by pshipton** [comment]
See https://github.com/ibmruntimes/Semeru-Runtimes/issues/22 and
