### ISSUE TITLE
libjsig.so / jsig.dll not required in vm directory

### ISSUE THREAD

**Issue by pshipton** [ibmruntimes/openj9-openjdk-jdk11#57]
#52 copies the jsig library into the places where it should be. It doesn't need to be in the compressedrefs/default directory.

**Comment by keithc-ca** [comment]
#52 didn't introduce the copy in the compressedrefs/default directory - it was always there.

**Comment by pshipton** [comment]
> #52 didn't introduce the copy in the compressedrefs/default directory - it was always there.

Understood. I didn't mean to imply that #52 added it. This Issue is a request for an "enhancement", to remove copies of libjsig.so / jsig.dll which are not required.
