### ISSUE TITLE
Source code jdk-11.0.1+13.tar.gz missed filles under directory closed/

### ISSUE THREAD

**Issue by gaolibj** [ibmruntimes/openj9-openjdk-jdk11#75]
I downloaded the source file from https://github.com/ibmruntimes/openj9-openjdk-jdk11/archive/jdk-11.0.1+13.tar.gz.  Seems it missed some files under directory closed/ , get_source.sh and README.md.

Is that work as design?

**Comment by pshipton** [comment]
This is as designed, the openj9 releases only contain open source.

**Comment by pshipton** [comment]
These tags correspond to the OpenJDK levels. There was not tag or release created for the OpenJ9 release.

**Comment by pshipton** [comment]
@andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
The jdk-11.0.1+13 tag is the OpenJDK commit tag, thus if you try and download that you will get the OpenJDK commit level of that code, not including the OpenJ9 Extensions.
What are you trying to retrieve?

**Comment by gaolibj** [comment]
I want to get  all source files of a specified level with zip format including OpenJ9 Extensions.  I don't care  OpenJDK commit level.  
Actually, I'm trying to build OpenJDK Version 11 with OpenJ9.  

The instructions to get source code at this page is "git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11.git".  With using this way,  the code will be changed everytime when I did a clone operation.  So, I hope to get a same level code every time.  
   
https://github.com/eclipse/openj9/blob/master/doc/build-instructions/Build_Instructions_V11.md#aix

**Comment by andrew-m-leonard** [comment]
It sounds as though you're trying to build a specific release? If you git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11.git each time you will be building "head"... If you want to build a specific release, you need to clone the repo, but checkout the latest openj9 release branch, which is for "openj9-0.11". So:
git clone https://github.com/ibmruntimes/openj9-openjdk-jdk11.git
git checkout openj9-0.11
get_source.sh
....
This will build the latest OpenJDK 11.0.1 with OpenJ9

**Comment by gaolibj** [comment]
Thanks.  I will try this way.
