### ISSUE TITLE
Running hotspot tests and got "Exception while calling user-specified class: requires.VMProps"

### ISSUE THREAD

**Issue by sophia-guo** [ibmruntimes/openj9-openjdk-jdk11#77]
https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/564/console

18:34:00 -jdk:"/home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/.." \
18:34:00 -exclude:"/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/ProblemList_openjdk11-openj9.txt" \
18:34:00 "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../openjdk_regression/openjdk-jdk/test/hotspot/jtreg/runtime/Nestmates"; \
18:34:00 if [ $? -eq 0 ] ; then echo ""; echo "runtime_nestmate_0""_PASSED"; echo ""; cd /home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../..;  else echo ""; echo "runtime_nestmate_0""_FAILED"; echo ""; fi; } 2>&1 | tee -a "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../TestConfig/test_output_15445496393623/TestTargetResult";
18:34:03 Directory "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/work" not found: creating
18:34:03 Directory "/home/jenkins/workspace/Grinder/openjdk-tests/TestConfig/scripts/testKitGen/../../../../jvmtest/openjdk_regression/report" not found: creating
18:34:14 Exception while calling user-specified class: requires.VMProps
18:34:14 java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
18:34:14 	at sun.hotspot.WhiteBox.<clinit>(WhiteBox.java:66)
18:34:14 	at requires.VMProps.<clinit>(VMProps.java:57)
18:34:14 	at java.base/java.lang.Class.forNameImpl(Native Method)
18:34:14 	at java.base/java.lang.Class.forName(Class.java:339)
18:34:14 	at com.sun.javatest.regtest.agent.GetJDKProperties.run(GetJDKProperties.java:78)
18:34:14 	at com.sun.javatest.regtest.agent.GetJDKProperties.main(GetJDKProperties.java:54)
18:34:14 Error: failed to get JDK properties for /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/java -ea -esa -Xmx512m -Xcompressedrefs; exit code 1

Should same changes as https://github.com/ibmruntimes/openj9-openjdk-jdk11/commit/802378583133ed647621d334327fcd3cef771b4a#diff-d8b9c32ba7ff50cca3a301dcfe5cb243 fix this?

**Comment by pshipton** [comment]
@andrew-m-leonard

**Comment by andrew-m-leonard** [comment]
Looks like wrong TEST.ROOT is being used, make sure you are using the extensions TEST.ROOT

**Comment by andrew-m-leonard** [comment]
@sophia-guo ^

**Comment by sophia-guo** [comment]
@andrew-m-leonard yes, grinder job https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/564/console use extension jdk as test resources. We will also updated to use extension as regular jobs. https://github.com/AdoptOpenJDK/openjdk-tests/pull/740.

The errors happened to Hotspot jtreg tests, which are using TEST.ROOT under https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/hotspot/jtreg/TEST.ROOT not the one under jdk https://github.com/ibmruntimes/openj9-openjdk-jdk11/blob/openj9/test/jdk/TEST.ROOT.

**Comment by andrew-m-leonard** [comment]
Why are we running a hotspot specific test again OpenJ9?

**Comment by sophia-guo** [comment]
Some of the tests  do actually apply to Openj9. We are planning to enable some Nestmates tests, which apply to Openj9. Details in https://github.ibm.com/runtimes/javanext/issues/15

**Comment by smlambert** [comment]
Can we get this issue addressed so that we can enable the Nestmate tests against OpenJ9 please?

**Comment by andrew-m-leonard** [comment]
This should now be resolved now we are auto-merging "tip" from openjdk, the testcases should now align...

**Comment by sophia-guo** [comment]
@andrew-m-leonard I'm not sure what do you mean by aligning testcases could resolve this problem?

I've tried and got same error: https://ci.adoptopenjdk.net/view/Test_grinder/job/Grinder/778/console

```
19:52:50 Exception while calling user-specified class: requires.VMProps
19:52:50 java.lang.UnsatisfiedLinkError: sun/hotspot/WhiteBox.registerNatives()V
19:52:50 	at sun.hotspot.WhiteBox.<clinit>(WhiteBox.java:66)
19:52:50 	at requires.VMProps.<clinit>(VMProps.java:57)
19:52:50 	at java.base/java.lang.Class.forNameImpl(Native Method)
19:52:50 	at java.base/java.lang.Class.forName(Class.java:339)
19:52:50 	at com.sun.javatest.regtest.agent.GetJDKProperties.run(GetJDKProperties.java:78)
19:52:50 	at com.sun.javatest.regtest.agent.GetJDKProperties.main(GetJDKProperties.java:54)
19:52:50 Error: failed to get JDK properties for /home/jenkins/workspace/Grinder/openjdkbinary/j2sdk-image/bin/../bin/java -ea -esa -Xmx512m -Xcompressedrefs; exit code 1

```
