### ISSUE TITLE
--with-openssl=<path> doesn't see to work with JDK11

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk11#80]
Has been ok on JDK8 but doesn't seem to like the same directory when I point to it in a JDK11 build.

I understand https://github.com/ibmruntimes/openj9-openjdk-jdk11/pull/79 was an initial attempt to fix it.

For now, I've modified the Linux/s390x build at adoptopenjdk to build from source, since that works with JDK11 but not JDK8 (Ref: https://github.com/AdoptOpenJDK/openjdk-build/pull/804)

We should resolve this for the future though.

```
checking if build directory is on local disk... yes
checking for OPENSSL... configure: error: Unable to find openssl in specified location /usr/local/openssl-1.1.1
no
configure exiting with result code 1
```

**Comment by groeges** [comment]
@sxa Is this still a problem? If not, can we close this issue?

**Comment by andrew-m-leonard** [comment]
This works fine on latest jdk11
