### ISSUE TITLE
Build failure when using fetched OpenSSL on Linux/s390x

### ISSUE THREAD

**Issue by sxa555** [ibmruntimes/openj9-openjdk-jdk11#81]
Using gcc 7.3. Ref: https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/52/console until that expires.

Had to switch to using `--with-openssl=fetched` instead of `--with-openssl=/usr/local/openssl-1.1.1` (which we use for building JDK8 on Linux/s390x) due to https://github.com/ibmruntimes/openj9-openjdk-jdk11/issues/80

```
Compiling 224 properties into resource bundles for jdk.localedata
Compiling 1 properties into resource bundles for jdk.jlink
Compiling 67 files for COMPILE_CREATE_SYMBOLS
Creating ct.sym classes
error: module not found: jdk.hotspot.agent
Creating support/symbols/ct.sym
Compiling 3085 files for java.base
ar: creating apps/libapps.a
crypto/sha/keccak1600-s390x.S: Assembler messages:
crypto/sha/keccak1600-s390x.S:356: Error: operand out of range (0xfffffffffffffff8 is not between 0x0000000000000000 and 0x0000000000000fff)
Makefile:4903: recipe for target 'crypto/sha/keccak1600-s390x.o' failed
gmake[5]: *** [crypto/sha/keccak1600-s390x.o] Error 1
gmake[5]: *** Waiting for unfinished jobs....
Makefile:171: recipe for target 'all' failed
gmake[4]: *** [all] Error 2
gmake[3]: *** [build_openssl] Error 1
/data/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-s390x-openj9/workspace/build/src/closed/openssl.gmk:41: recipe for target 'build_openssl' failed
/data/jenkins/workspace/build-scripts/jobs/jdk11u/jdk11u-linux-s390x-openj9/workspace/build/src/closed/make/Main.gmk:42: recipe for target 'openssl-build' failed
gmake[2]: *** [openssl-build] Error 2
```

**Comment by pshipton** [comment]
Seems to be working here https://ci.eclipse.org/openj9/job/Build-JDK11-linux_390-64_cmprssptrs/314
`./get_source.sh --openssl-version=1.1.1`
`configure ... --with-openssl=fetched --enable-openssl-bundling`
`00:26:30 checking for OPENSSL... yes`
`00:26:43 Compiling OpenSSL in /home/jenkins/jenkins-agent/workspace/Build-JDK11-linux_390-64_cmprssptrs/openssl`
`00:26:44 Configuring OpenSSL version 1.1.1 (0x1010100fL) for linux64-s390x`

@enasser

**Comment by enasser** [comment]
Thank you @pshipton. Does it mean that when we fetch and build openssl, it is working but not with pre-built openssl. Based on the error message, it's an issue with the openssl pre-built binary.  @sxa555 please  try with the latest 1.1.1 level as pre-built binary.

**Comment by sxa555** [comment]
Based on the options (see https://ci.adoptopenjdk.net/job/build-scripts/job/jobs/job/jdk11u/job/jdk11u-linux-s390x-openj9/59/consoleFull) it should be using a version built during the build process now

**Comment by groeges** [comment]
@sxa Is this still an issue?

**Comment by sxa555** [comment]
I'm happy for this to be closed - We're building using `--with-openssl-system` now anyway.
