### ISSUE TITLE
32-bit MSVC toolchain is used when 64-bit ones are available

### ISSUE THREAD

**Issue by 0dvictor** [ibmruntimes/openj9-openjdk-jdk11#85]
autoconf always picks 32-bit MSVC toolchain even if 64-bit ones are available. By switching to 64-bit toolchain, the compilation time is significantly reduced. Disassembly of JIT dll generates by 32-bit and 64-bit toolchains confirms identical codes have been generated.

**Comment by andrew-m-leonard** [comment]
actually think about this, this is not relevant any more as jdk11+ only supports 64bit build platforms, 32bit no longer supported.
