### ISSUE TITLE
java.management.jmod and jdk.management.jmod on AIX include different classes with HotSpot OpenJDK 11

### ISSUE THREAD

**Issue by gaolibj** [ibmruntimes/openj9-openjdk-jdk11#86]
java.management.jmod and jdk.management.jmod on AIX include different classes with HotSpot OpenJDK 11.    Does  it work as design?  If so, I want to know how you passed Java11 regression test on AIX.   I found some classes are required by Java 11 regression test.   

Some classes are required and I can find the source code, but they are not  included in the corresponding   jmod files, like java.management.jmod and jdk.management.jmod.

src/jdk.management/share/classes/com/sun/management/VMOption.java
src/java.management/share/classes/sun/management/ThreadInfoCompositeData.java
src/java.management/share/classes/sun/management/HotspotRuntimeMBean.java
src/java.management/share/classes/sun/management/HotspotClassLoadingMBean.java
src/java.management/share/classes/sun/management/LazyCompositeData.java
src/java.management/share/classes/sun/management/StackTraceElementCompositeData.java
src/java.management/share/classes/sun/management/ManagementFactoryHelper.java
src/java.management/share/classes/sun/management/MemoryUsageCompositeData.java
src/java.management/share/classes/sun/management/ThreadInfoCompositeData.java

**Result of Openj9 OpenJDK 11 on AIX.:**
bash-4.4$ ../bin/jmod list jdk.management.jmod | grep "com/sun/management"
classes/com/sun/management/DiagnosticCommandMBean.class
classes/com/sun/management/GarbageCollectionNotificationInfo.class
classes/com/sun/management/GarbageCollectorMXBean.class
classes/com/sun/management/GcInfo.class
classes/com/sun/management/HotSpotDiagnosticMXBean.class
classes/com/sun/management/OperatingSystemMXBean.class
classes/com/sun/management/ThreadMXBean.class
classes/com/sun/management/UnixOperatingSystemMXBean.class
classes/com/sun/management/internal/GarbageCollectionNotificationInfoUtil.class
classes/com/sun/management/internal/GcInfoUtil$1.class
classes/com/sun/management/internal/GcInfoUtil.class

**Result of HotSpot OpenJDK 11 on Mac.:(There is no AIX version, so I tried mac version)**
bash-4.2$ ../bin/jmod list jdk.management.jmod | grep "com/sun/management"
classes/com/sun/management/DiagnosticCommandMBean.class
classes/com/sun/management/GarbageCollectionNotificationInfo.class
classes/com/sun/management/GarbageCollectorMXBean.class
classes/com/sun/management/GcInfo.class
classes/com/sun/management/HotSpotDiagnosticMXBean.class
classes/com/sun/management/internal/DiagnosticCommandArgumentInfo.class
classes/com/sun/management/internal/DiagnosticCommandImpl$OperationInfoComparator.class
classes/com/sun/management/internal/DiagnosticCommandImpl$Wrapper.class
classes/com/sun/management/internal/DiagnosticCommandImpl.class
classes/com/sun/management/internal/DiagnosticCommandInfo.class
classes/com/sun/management/internal/Flag$1.class
classes/com/sun/management/internal/Flag.class
classes/com/sun/management/internal/GarbageCollectionNotifInfoCompositeData$1.class
classes/com/sun/management/internal/GarbageCollectionNotifInfoCompositeData.class
classes/com/sun/management/internal/GarbageCollectorExtImpl.class
classes/com/sun/management/internal/GcInfoBuilder.class
classes/com/sun/management/internal/GcInfoCompositeData$1.class
classes/com/sun/management/internal/GcInfoCompositeData$2.class
classes/com/sun/management/internal/GcInfoCompositeData.class
classes/com/sun/management/internal/HotSpotDiagnostic.class
classes/com/sun/management/internal/HotSpotThreadImpl.class
classes/com/sun/management/internal/OperatingSystemImpl.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl$1.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl$2.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl$3.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl$4.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl$5.class
classes/com/sun/management/internal/PlatformMBeanProviderImpl.class
classes/com/sun/management/internal/VMOptionCompositeData.class
classes/com/sun/management/OperatingSystemMXBean.class
classes/com/sun/management/ThreadMXBean.class
classes/com/sun/management/UnixOperatingSystemMXBean.class
classes/com/sun/management/**VMOption$Origin.class**
classes/com/sun/management/**VMOption.class**

**Result of Openj9 OpenJDK 11 on AIX.:**
bash-4.4$ ../bin/jmod list java.management.jmod | grep "sun/management"
classes/sun/management/Util.class
classes/sun/management/counter/AbstractCounter$Flags.class
classes/sun/management/counter/AbstractCounter.class
classes/sun/management/counter/ByteArrayCounter.class
classes/sun/management/counter/Counter.class
classes/sun/management/counter/LongArrayCounter.class
classes/sun/management/counter/LongCounter.class
classes/sun/management/counter/StringCounter.class
classes/sun/management/counter/Units.class
classes/sun/management/counter/Variability.class
classes/sun/management/counter/perf/ByteArrayCounterSnapshot.class
classes/sun/management/counter/perf/InstrumentationException.class
classes/sun/management/counter/perf/LongArrayCounterSnapshot.class
classes/sun/management/counter/perf/LongCounterSnapshot.class
classes/sun/management/counter/perf/PerfByteArrayCounter.class
classes/sun/management/counter/perf/PerfDataEntry$EntryFieldOffset.class
classes/sun/management/counter/perf/PerfDataEntry.class
classes/sun/management/counter/perf/PerfDataType.class
classes/sun/management/counter/perf/PerfInstrumentation.class
classes/sun/management/counter/perf/PerfLongArrayCounter.class
classes/sun/management/counter/perf/PerfLongCounter.class
classes/sun/management/counter/perf/PerfStringCounter.class
classes/sun/management/counter/perf/Prologue$PrologueFieldOffset.class
classes/sun/management/counter/perf/Prologue.class
classes/sun/management/counter/perf/StringCounterSnapshot.class
classes/sun/management/spi/PlatformMBeanProvider$PlatformComponent.class
classes/sun/management/spi/PlatformMBeanProvider.class

**Result of HotSpot OpenJDK 11 on Mac.:**
classes/sun/management/BaseOperatingSystemImpl.class
classes/sun/management/ClassLoadingImpl.class
classes/sun/management/CompilationImpl.class
classes/sun/management/CompilerThreadStat.class
classes/sun/management/counter/AbstractCounter$Flags.class
classes/sun/management/counter/AbstractCounter.class
classes/sun/management/counter/ByteArrayCounter.class
classes/sun/management/counter/Counter.class
classes/sun/management/counter/LongArrayCounter.class
classes/sun/management/counter/LongCounter.class
classes/sun/management/counter/perf/ByteArrayCounterSnapshot.class
classes/sun/management/counter/perf/InstrumentationException.class
classes/sun/management/counter/perf/LongArrayCounterSnapshot.class
classes/sun/management/counter/perf/LongCounterSnapshot.class
classes/sun/management/counter/perf/PerfByteArrayCounter.class
classes/sun/management/counter/perf/PerfDataEntry$EntryFieldOffset.class
classes/sun/management/counter/perf/PerfDataEntry.class
classes/sun/management/counter/perf/PerfDataType.class
classes/sun/management/counter/perf/PerfInstrumentation.class
classes/sun/management/counter/perf/PerfLongArrayCounter.class
classes/sun/management/counter/perf/PerfLongCounter.class
classes/sun/management/counter/perf/PerfStringCounter.class
classes/sun/management/counter/perf/Prologue$PrologueFieldOffset.class
classes/sun/management/counter/perf/Prologue.class
classes/sun/management/counter/perf/StringCounterSnapshot.class
classes/sun/management/counter/StringCounter.class
classes/sun/management/counter/Units.class
classes/sun/management/counter/Variability.class
classes/sun/management/GarbageCollectorImpl.class
classes/sun/management/HotspotClassLoading.class
classes/sun/management/**HotspotClassLoadingMBean.class**
classes/sun/management/HotspotCompilation$CompilerThreadInfo.class
classes/sun/management/HotspotCompilation.class
classes/sun/management/HotspotCompilationMBean.class
classes/sun/management/HotspotInternal.class
classes/sun/management/HotspotInternalMBean.class
classes/sun/management/HotspotMemory.class
classes/sun/management/HotspotMemoryMBean.class
classes/sun/management/HotspotRuntime.class
classes/sun/management/**HotspotRuntimeMBean.class**
classes/sun/management/HotspotThread.class
classes/sun/management/HotspotThreadMBean.class
classes/sun/management/**LazyCompositeData.class**
classes/sun/management/LockInfoCompositeData.class
classes/sun/management/ManagementFactoryHelper$1.class
classes/sun/management/ManagementFactoryHelper$2.class
classes/sun/management/ManagementFactoryHelper$3.class
classes/sun/management/ManagementFactoryHelper$LoggingMXBeanAccess$1.class
classes/sun/management/ManagementFactoryHelper$LoggingMXBeanAccess.class
classes/sun/management/ManagementFactoryHelper$PlatformLoggingImpl.class
classes/sun/management/**ManagementFactoryHelper.class**
classes/sun/management/MappedMXBeanType$ArrayMXBeanType.class
classes/sun/management/MappedMXBeanType$BasicMXBeanType.class
classes/sun/management/MappedMXBeanType$CompositeDataMXBeanType$1.class
classes/sun/management/MappedMXBeanType$CompositeDataMXBeanType$2.class
classes/sun/management/MappedMXBeanType$CompositeDataMXBeanType.class
classes/sun/management/MappedMXBeanType$EnumMXBeanType.class
classes/sun/management/MappedMXBeanType$GenericArrayMXBeanType.class
classes/sun/management/MappedMXBeanType$InProgress.class
classes/sun/management/MappedMXBeanType$ListMXBeanType.class
classes/sun/management/MappedMXBeanType$MapMXBeanType.class
classes/sun/management/MappedMXBeanType.class
classes/sun/management/MemoryImpl.class
classes/sun/management/MemoryManagerImpl.class
classes/sun/management/MemoryNotifInfoCompositeData.class
classes/sun/management/MemoryPoolImpl$CollectionSensor.class
classes/sun/management/MemoryPoolImpl$PoolSensor.class
classes/sun/management/MemoryPoolImpl.class
classes/sun/management/**MemoryUsageCompositeData.class**
classes/sun/management/MethodInfo.class
classes/sun/management/MonitorInfoCompositeData.class
classes/sun/management/NotificationEmitterSupport$ListenerInfo.class
classes/sun/management/NotificationEmitterSupport.class
classes/sun/management/RuntimeImpl.class
classes/sun/management/Sensor.class
classes/sun/management/spi/PlatformMBeanProvider$PlatformComponent.class
classes/sun/management/spi/PlatformMBeanProvider.class
classes/sun/management/**StackTraceElementCompositeData.class**
classes/sun/management/ThreadImpl.class
classes/sun/management/ThreadInfoCompositeData$ThreadInfoCompositeTypes.class
classes/sun/management/**ThreadInfoCompositeData.class**
classes/sun/management/Util.class
classes/sun/management/VMManagement.class
classes/sun/management/VMManagementImpl$1.class
classes/sun/management/VMManagementImpl.class

**Comment by pshipton** [comment]
@gaolibj It is by design that the management extensions and implementations are different. OpenJDK regression tests that do not apply to OpenJ9 are excluded. Also it is WIP to fix some remaining regression test failures, see https://github.com/eclipse/openj9/projects/8

@smlambert

**Comment by smlambert** [comment]
Yes, to confirm, not all openjdk regression tests are applicable to the openjdk-openj9 implementation.  There are a lot of openjdk-hotspot specific tests in that suite of tests.  

We run a subset of those tests against the openj9 implementation at the AdoptOpenJDK project (and are still in the process of excluding tests that are not applicable for jdk11).  You can see the set of [jdk_management tests that were excluded](https://github.com/AdoptOpenJDK/openjdk-tests/blob/master/openjdk_regression/ProblemList_openjdk8-openj9.txt#L67-L117) for jdk8-openj9.  Still need to do the same for jdk11 at the Adopt project.

OpenJ9 has its own set of functional/regression tests that are run (~20,000 and growing), to test that the overall functionality works as the spec defines.

**Comment by zhuohual** [comment]
@smlambert 
Do you mean that currently there are more than 20000 test cases for OpenJ9?
Are these test cases all from openjdk repository?

**Comment by zhuohual** [comment]
@smlambert 
By the way, I check the jdk_management exclude list both in ProblemList_openjdk8-openj9.txt and in ProblemList_openjdk11-openj9.txt. I found they only existed in ProblemList_openjdk8-openj9.txt. So according to your comments, we also need to append them to the ProblemList_openjdk11-openj9.txt , correct?

**Comment by smlambert** [comment]
The ~20000 test cases are in the openj9 repository, in [test/functional](https://github.com/eclipse/openj9/tree/master/test/functional) dir.  We run them at the[ openj9 project](https://ci.eclipse.org/openj9/view/Test/), example output [here](https://ci.eclipse.org/openj9/view/Test/job/Test-sanity.functional-JDK11-linux_x86-64_cmprssptrs/326/testReport/).

And yes, you are correct, my comment indicates that we should update ProblemList_openjdk11-openj9.txt to exclude the tests that are not applicable to openj9.  It simply has not been done yet.

**Comment by andrew-m-leonard** [comment]
I think this is resolved as "by design"
